<?php

function mailjet($subject = '', $email = '', $html = '')
{
  $conf = [
    'MJ_APIKEY_PUBLIC' => '',
    'MJ_APIKEY_PRIVATE' => '',
    'FromEmail' => 'email@email.com',
    'FromName' => 'Nombre del enviador',
  ];

  $data = [
    "FromEmail" => $conf["FromEmail"],
    "FromName" => $conf["FromName"],
    "Subject" => $subject,
    "Text-part" => strip_tags($html),
    "Html-part" => $html,
    "Recipients" => [
      [
        "Email" => $email
      ]
    ]
  ];

  // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
  $ch = curl_init();

  curl_setopt($ch, CURLOPT_URL, 'https://api.mailjet.com/v3/send');
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
  curl_setopt($ch, CURLOPT_USERPWD, $conf["MJ_APIKEY_PUBLIC"] . ':' . $conf["MJ_APIKEY_PRIVATE"]);

  $headers = array();
  $headers[] = 'Content-Type: application/json';
  curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

  $result = curl_exec($ch);
  if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
  }
  curl_close($ch);
}
